### ISSUE TITLE
Compile error on latest commit 

### ISSUE THREAD

**Issue by prideofconcept** [Aloshi/dukglue#10]
### Awesome project 

I can compile and use commit [d9de02b](https://github.com/Aloshi/dukglue/commit/d9de02b0c9807b779e7f9d639fb7eb0430dc7083)
but the latest commit 49be83c0 seems to fail.

( Compiling on Mac with Clang 5 )
 \- ( if I add detail_primitive_type.h I get template specification errors )

`In file included from {REDACTED}demo/demo-dukglue.cpp:3:
In file included from {REDACTED}external/dukglue/include/dukglue/dukglue.h:3:
In file included from {REDACTED}external/dukglue/include/dukglue/register_function.h:3:
In file included from {REDACTED}external/dukglue/include/dukglue/detail_function.h:3:
In file included from {REDACTED}external/dukglue/include/dukglue/detail_stack.h:6:
{REDACTED}external/dukglue/include/dukglue/detail_types.h:60:97: error: use of undeclared identifier 'get_type_name'
                                        duk_error(ctx, DUK_RET_TYPE_ERROR, "Argument %d: expected native object, got %s", arg_idx, get_type_name(type_idx));`

### dukglue/include/dukglue/detail_types.h:60:97: error: use of undeclared identifier 'get_type_name'

`duk_error(ctx, DUK_RET_TYPE_ERROR, "Argument %d: expected native object, got %s", arg_idx, get_type_name(type_idx));`

**Comment by desertkun** [comment]
Same. Did you manage to resolve this?

**Comment by prideofconcept** [comment]
Unfortunately not, just chose to keep moving with the previous working commit
